### ISSUE TITLE
unable to upload templates

### ISSUE THREAD

**Issue by medea61** [vmware/container-service-extension#124] opened 2018-10-08 17:51 UTC
I am trying to run an installation against vCD 9.5 in our lab. The installation fails at uploading templates. It basically start the upload (vCD tasks at 1%) but fails after ~2MB of the .vmdk files.

Any ideas?

```
[vmware@cse-1 ~]$ cse install --config config.yaml
Validating CSE on vCD from file: config.yaml
Python version >= 3.6 (installed: 3.6.5): success
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to AMQP server (<REDACTED>:5672): success
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director as system administrator (<REDACTED>:443): success
Connected to vCenter Server <REDACTED> as administrator@<REDACTED> (<REDACTED>:443): success
Installing CSE on vCD from file: config.yaml, template: *
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director as system administrator (<REDACTED>:443): success
Installing  'default' service broker
Find org '<REDACTED>': success
Find vdc '<REDACTED>': success
Found catalog <REDACTED>
Processing template: photon-v2
Creating template
Uploading photon-custom-hw11-2.0-304b817.ova
Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 398, in create_template
    template['source_ova_name'])
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 288, in get_catalog_item
    raise EntityNotFoundException('Catalog item not found.')
pyvcloud.vcd.exceptions.EntityNotFoundException: Catalog item not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 649, in upload_ovf
    callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 716, in _upload_file
    file_name, target_uri, chunk_size=chunk_size, callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 793, in _upload_part_file
    self.client.upload_fragment(target_uri, data, range_str)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 936, in upload_fragment
    verify=self._verify_ssl_certs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 398, in create_template
    template['source_ova_name'])
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 288, in get_catalog_item
    raise EntityNotFoundException('Catalog item not found.')
pyvcloud.vcd.exceptions.EntityNotFoundException: Catalog item not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 649, in upload_ovf
    callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 716, in _upload_file
    file_name, target_uri, chunk_size=chunk_size, callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 793, in _upload_part_file
    self.client.upload_fragment(target_uri, data, range_str)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 936, in upload_fragment
    verify=self._verify_ssl_certs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 287, in install_cse
    catalog, no_capture, template, ssh_key)
  File "/home/vmware/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 400, in create_template
    source_ova_item = upload_source_ova(config, client, org, template)
  File "/home/vmware/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 372, in upload_source_ova
    callback=None)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 653, in upload_ovf
    e.__traceback__)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 649, in upload_ovf
    callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 716, in _upload_file
    file_name, target_uri, chunk_size=chunk_size, callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 793, in _upload_part_file
    self.client.upload_fragment(target_uri, data, range_str)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 936, in upload_fragment
    verify=self._verify_ssl_certs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
pyvcloud.vcd.exceptions.UploadException: Ovf upload failed

Can't create or update template 'photon-v2' 'CSE': photon-custom-hw11-2.0-304b817-k8s
Processing template: ubuntu-16.04
Creating template
Uploading ubuntu-16.04-server-cloudimg-amd64.ova
Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 398, in create_template
    template['source_ova_name'])
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 288, in get_catalog_item
    raise EntityNotFoundException('Catalog item not found.')
pyvcloud.vcd.exceptions.EntityNotFoundException: Catalog item not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 649, in upload_ovf
    callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 716, in _upload_file
    file_name, target_uri, chunk_size=chunk_size, callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 793, in _upload_part_file
    self.client.upload_fragment(target_uri, data, range_str)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 936, in upload_fragment
    verify=self._verify_ssl_certs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 398, in create_template
    template['source_ova_name'])
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 288, in get_catalog_item
    raise EntityNotFoundException('Catalog item not found.')
pyvcloud.vcd.exceptions.EntityNotFoundException: Catalog item not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/vmware/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 649, in upload_ovf
    callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 716, in _upload_file
    file_name, target_uri, chunk_size=chunk_size, callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 793, in _upload_part_file
    self.client.upload_fragment(target_uri, data, range_str)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 936, in upload_fragment
    verify=self._verify_ssl_certs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 287, in install_cse
    catalog, no_capture, template, ssh_key)
  File "/home/vmware/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 400, in create_template
    source_ova_item = upload_source_ova(config, client, org, template)
  File "/home/vmware/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 372, in upload_source_ova
    callback=None)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 653, in upload_ovf
    e.__traceback__)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 649, in upload_ovf
    callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 716, in _upload_file
    file_name, target_uri, chunk_size=chunk_size, callback=callback)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 793, in _upload_part_file
    self.client.upload_fragment(target_uri, data, range_str)
  File "/home/vmware/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 936, in upload_fragment
    verify=self._verify_ssl_certs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
pyvcloud.vcd.exceptions.UploadException: Ovf upload failed

Can't create or update template 'ubuntu-16.04' 'CSE': ubuntu-16.04-server-cloudimg-amd64-k8s
AMQP settings are the same, skipping AMQP configuration
Find extension 'cse', enabled=true: success
Start CSE with: 'cse run config.yaml'
[vmware@cse-1 ~]$
```

**Comment by medea61** [comment] 2018-10-08 17:53
PS: I applied the suggested fix of #92 as this is backed by vCenter 6.7

**Comment by medea61** [comment] 2018-10-08 19:45
this looks like it is an issue in the underlaying vcd-cli / pyvcloud libraries. i found an open issue which sounds related in vcd-cli (https://github.com/vmware/vcd-cli/issues/249).

**Comment by rocknes** [comment] 2018-10-08 19:56
Yes this issue seems to be same as https://github.com/vmware/vcd-cli/issues/249
``BrokenPipeError: [Errno 32] Broken pipe`` - vCD is hanging up on the connection.

vCD team is aware of this bug, and it's being tracked internally. I will get in touch with them and try to see if they can find out why vCD is closing the connection on clients.

**Comment by rocknes** [comment] 2018-10-09 18:30
I am unable to reproduce the issue with vCD 9.5GA build.

But I have identified an issue in the way pyvlcoud uploads files, the Content-Range header has wrong values set in it. I can mail you a pyvcloud wheel file with a fix to the Content-Range issue. Can you please test out uploading an ovf with the fix in? If that works I will push the change to vmware/pyvcloud:master.

**Comment by rocknes** [comment] 2018-10-11 19:10
@medea61 https://github.com/vmware/vcd-cli/issues/249 has been resolved. It turned out to be a load balancer configuration issue. On a side note, I will push out a change on pyvcloud which will fix the Content Range header issue. You can follow the workaround mentioned in the other issue for the time being to upload templates to vCD.

**Comment by rocknes** [comment] 2018-10-12 18:31
Submitted change to pyvclud via https://github.com/vmware/pyvcloud/pull/303 .
Closing this ticket.

**Closed by rocknes** 2018-10-12 18:31 UTC
Labels: bug
