### ISSUE TITLE
Misleading error message in cse client if cse server is not available

### ISSUE THREAD

**Issue by tschoergez** [vmware/container-service-extension#196] opened 2019-01-11 20:45 UTC
When trying to run the vcd cse client commands, and the server is not available, an error message 

> Error: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)

vcd.log on the client points to the fact that the server is not answering:
> 2019-01-11 20:04:51,253 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request uri (GET): https://vcd.lab.o11n.com/api/cse/template
> 2019-01-11 20:04:51,253 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request headers: {'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/*+json;version=31.0', 'Connection': 'keep-alive', 'x-vcloud-authorization': '3dd1e4e9c1544d8ca461dc14ce835010'}
> 2019-01-11 20:04:51,253 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response status code: 504
> 2019-01-11 20:04:51,253 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response headers: {'Date': 'Fri, 11 Jan 2019 20:04:51 GMT', 'X-VMWARE-VCLOUD-REQUEST-ID': 'a643aee3-dbb6-44ae-83ee-3e843aaf527d', 'X-VMWARE-VCLOUD-CEIP-ID': 'fa59df63-1e43-4384-bf81-dbf716acd5aa', 'X-VMWARE-VCLOUD-ACCESS-TOKEN': 'eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhY21lLWFkbWluIiwiaXNzIjoiN2Y5OTUyMGItNGM5MC00Njc4LTg1MzMtYTE3N2Q1OGJlMDg4QDE5ZTVmZjM5LTVjYjgtNGYzNS05YzA0LWYwNTk4ODllYjU0NSIsImV4cCI6MTU0NzMyMzI5MSwidmVyc2lvbiI6InZjbG91ZF8xLjAiLCJqdGkiOiIzZGQxZTRlOWMxNTQ0ZDhjYTQ2MWRjMTRjZTgzNTAxMCJ9.xXP4XjS1X0M86kackF4XlcsioQZySUtjZdmGe5F3jje4rSATim4HlR_ErSA9JYknuotDTSEcIo7VHZNgHMylxDhZ2zypejTXK2mgPfZuYaApwcw-eCgVbIkF61vW9PQWRMjXoCw7rIndTSolWIWcpPCux8Ee-GqLG-E0dT-PoPpvrEsj0CEU6abrlt_isZS9Bl1VmgZm3jMXHaGiWgdlGx1tPLJDoo9IYcJHJk0vw_xjBcD80VlXJH8iBmrnPFTvnHQdQSns80WKkOKMS7lmMRBMyOSwT3wRcDdDgTG7kXtfjUX1nSDcSKqCAGJq5N8NSDeY5-fWpM4wwLfnfE1_fQ', 'X-VMWARE-VCLOUD-TOKEN-TYPE': 'Bearer', 'x-vcloud-authorization': '3dd1e4e9c1544d8ca461dc14ce835010', 'Content-Type': 'application/vnd.vmware.vcloud.error+json;version=31.0', 'X-VMWARE-VCLOUD-REQUEST-EXECUTION-TIME': '10107', 'Transfer-Encoding': 'chunked'}
> 2019-01-11 20:04:51,253 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response body: {
>   "otherAttributes" : { },
>   "tenantError" : null,
>   "stackTrace" : null,
>   "majorErrorCode" : 504,
>   "message" : "External service 'cse' failed to respond in the specified timeout (10 SECONDS)",
>   "minorErrorCode" : "GATEWAY_TIMEOUT",
>   "vendorSpecificErrorCode" : null,
>   "vcloudExtension" : [ ]
> }
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/container_service_extension/client/cse.py", line 112, in list_templates
>     templates = cluster.get_templates()
>   File "/usr/lib/python3.6/site-packages/container_service_extension/client/cluster.py", line 52, in get_templates
>     return self._process_response(response)
>   File "/usr/lib/python3.6/site-packages/container_service_extension/client/cluster.py", line 22, in _process_response
>     obj = objectify.fromstring(response.content)
>   File "src/lxml/objectify.pyx", line 1802, in lxml.objectify.fromstring
>   File "src/lxml/etree.pyx", line 3211, in lxml.etree.fromstring
>   File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
>   File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
>   File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
>   File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
>   File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
>   File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
>   File "<string>", line 1
> lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

Is that some API version mismatch (JSON vs. XML error message in vCD API response)?

**Comment by andrew-ni** [comment] 2019-01-29 01:07
Sorry, we haven't been able to reproduce this error. When the server is not running, I get this error:
```Error: External service 'cse' failed to respond in the specified timeout (10 SECONDS)```

What kind of user are you logged in as? and what are the exact commands you're running?

I don't think this should be an API version mismatch error, but we'll continue investigating.

**Comment by tschoergez** [comment] 2019-02-13 21:29
In my case, I'm logged in as an organization admin user, and try to run
vcd cse cluster list

**Comment by paulklassen** [comment] 2019-02-26 06:20
Hi tschoergez, make sure the CSE service is running with the correct config.yaml file and that the config.yaml file has the correct amqp server configured.
This was the problem in my case, since we use two vCloud Director servers and one of them wasn't working correct.

**Comment by andrew-ni** [comment] 2019-07-01 21:38
Fixed in #371

**Closed by andrew-ni** 2019-07-01 21:38 UTC
Labels: bug, known issue
