### ISSUE TITLE
Unable to install CSE, check and install parameter fails with remote host force closure

### ISSUE THREAD

**Issue by Yashwantk5888** [vmware/container-service-extension#1018] opened 2021-04-22 09:18 UTC
PS C:\Users\Administrator> cse check .\ec-vcdcse-config.yaml
Required Python version: >= 3.7.3
Installed Python version: 3.9.4 (tags/v3.9.4:1f2e308, Apr  4 2021, 13:27:16) [MSC v.1928 64 bit (AMD64)]
Password for config file decryption:
Decrypting '.\ec-vcdcse-config.yaml'
Validating config file '.\ec-vcdcse-config.yaml'
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director (is-dhcp38-154.isl.xxx.com:443)
Connected to vCenter Server 'is-dhcp38-226.isl.xxx.com' as 'administrator@xxx.local' (is-dhcp38-226.isl.xxx.com)
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by Yashwantk5888** [comment] 2021-04-22 09:25
Is there any debug parameter i can add to see what is that remote host.  CSE server and client are on same machine which has internet access even for the VCD cells has internet access.

**Comment by Yashwantk5888** [comment] 2021-04-22 09:28
PS C:\Users\Administrator> cse version
CSE, Container Service Extension for VMware vCloud Director, version 3.0.2

PS C:\Users\Administrator> vcd version
vcd-cli, VMware vCloud Director Command Line Interface, 24.0.1

**Comment by Yashwantk5888** [comment] 2021-04-23 15:12
Can anyone look into this

**Comment by Anirudh9794** [comment] 2021-05-18 22:30
Hello,
Sorry for the late reply.
Can you please verify if you are able to do a curl on the `remote_template_cookbook_url` in your config?

Thanks,
Aniruddha

**Comment by Anirudh9794** [comment] 2021-07-19 21:37
Hello @Yashwantk5888,
Were you able to solve the issue?
10054 error usually happens if there is congestion. As I noted above, the issue is most likely with the `remote_template_cookbook_url`

**Comment by Anirudh9794** [comment] 2021-07-26 17:46
Hello @Yashwantk5888 ,
With CSE 3.0.4, we have added more descriptive error messages when CSE fails to connect to remote template repository.
Please upgrade to CSE 3.0.4 to fix this issue.
I am closing this issue for now, but if you still face the same issue after upgrading, please re-open the issue.

Thanks,
Aniruddha

**Closed by Anirudh9794** 2021-07-26 17:46 UTC
Labels: bug

**Comment by Yashwantk5888** [comment] 2021-07-27 17:51
Thanks .. I'll try the latest cse..
