### ISSUE TITLE
x-vcloud-authorization error

### ISSUE THREAD

**Issue by stephaneclavel** [vmware/container-service-extension#500] opened 2020-01-15 14:01 UTC
Hi

I currently face an error x-vcloud-authorization when trying to use vcd cse commands on one of our system (recently installed) while same commands are working on a system that was installed 2 weeks before: 

system working fine: 

[cse@vCD10-CSE cse-logs]$ vcd login vcd10.xxxxx tenant1 cse -p xxxxxxx -w -i
cse logged in, org: 'tenant1', vdc: 'tenant1-cse-vdc'
[cse@vCD10-CSE cse-logs]$ vcd cse system info
property     value
-----------  ------------------------------------------------------
description  Container Service Extension for VMware vCloud Director
product      CSE
version      2.5.1

system not working fine:

(cse-env) [cse@vcd10-cseclient3-venv ~]$ vcd login vcd10.xxxx tenant1 cse -p xxxxxxxx -iw
cse logged in, org: 'tenant1', vdc: 'tenant1-cse-vdc'
(cse-env) [cse@vcd10-cseclient3-venv ~]$ vcd cse system info
Usage: vcd cse system info [OPTIONS]
Try "vcd cse system info -h" for help.

Error: 'x-vcloud-authorization'

I can't spot where the error comes from, any help/guidance appreciated please. 

thanks in advance

**Comment by rocknes** [comment] 2020-01-16 19:23
Hi Stephan, 

Did you update pyvcloud/vcd-cli recently? Some changes have been made to pyvcloud recently that stop reliance on x-vcloud-authorization header for authorization and instead use standard JWT based authorization tokens.

I suspect that you have the latest dev builds of pyvcloud and vcd-cli installed on your system. If you revert them back to the released versions. I believe the issue should go away.

Regards
Aritra Sen

**Comment by stephaneclavel** [comment] 2020-01-16 19:41
Hello Aritra

Thanks for your response. 

The non working system was installed in 2020. 

I already reverted vcd-cli to previous build as per https://github.com/vmware/vcd-cli/issues/511

I also tried to revert to container-service-extension previous build without success. 

How shall I revert pyvcloud? I installed vcd-cli and container-service-extension only, I assume pyvcloud is embedded? 

thanks

**Comment by rocknes** [comment] 2020-01-17 00:26
Hi Stephan,

I have updated the other issue with root cause and fix. This is an unfortunate version mismatch of vcd-cli and pyvcloud :(
You can easily fix this issue via the workaround I mentioned in the other thread. Let me know if you face any other issues.

Regards
Aritra Sen

**Comment by rocknes** [comment] 2020-01-17 21:32
Work around and root cause : https://github.com/vmware/vcd-cli/issues/511#issuecomment-575375346

Will keep this issue open until next version of vcd-cli is released.

**Comment by rocknes** [comment] 2020-02-27 23:23
pyvcloud 22.0.0 and vcd-cli 23.0.0 has been released. Closing this issue

**Closed by rocknes** 2020-02-27 23:23 UTC
Labels: known issue

**Comment by kam1sh** [comment] 2020-09-11 09:07
Hi! It looks like I'm having the same issue with latest versions of VCD and CSE:
```
> vcd cse system info
Usage: vcd cse system info [OPTIONS]
Try 'vcd cse system info -h' for help.

Error: 'x-vcloud-authorization'
```
**Versions**:
vCloud Director version: 10.0.0.16081830 Wed Apr 22 09:07:15 UTC 2020
Packages and Python:
```
> pip3 freeze | grep -E 'container|vcd'
container-service-extension==2.6.1
vcd-api-schemas-type==9.1.2.dev10
vcd-cli==23.0.0
> python3 -V
Python 3.8.0
```
This issue stays on all CSE versions after 2.0.0, on 2.0.0 there is another error:
```
Traceback (most recent call last):
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/container_service_extension/client/cse.py", line 693, in info
    result = system.get_info()
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/container_service_extension/client/system.py", line 24, in get_info
    return process_response(response)
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/container_service_extension/utils.py", line 158, in process_response
    response_to_exception(response)
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/container_service_extension/utils.py", line 214, in response_to_exception
    raise VcdResponseError(response.status_code, message)
container_service_extension.exceptions.VcdResponseError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igor/.pyenv/versions/3.8.0/bin/vcd", line 8, in <module>
    sys.exit(vcd())
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/container_service_extension/client/cse.py", line 696, in info
    stderr(e, ctx)
  File "/home/igor/.pyenv/versions/3.8.0/lib/python3.8/site-packages/vcd_cli/utils.py", line 263, in stderr
    message = str(exception)
TypeError: __str__ returned non-string (type dict)
```

I'll be very thankful if you could help me with that =)
