### ISSUE TITLE
[CSE UI] Cluster create wizard - networks are not displayed if the org vdc name has space(s)

### ISSUE THREAD

**Issue by wynner** [vmware/container-service-extension#625] opened 2020-06-22 10:14 UTC
When creating a new K8s cluster the network selection part of the wizard doesn't populate the list of available Tenant networks.
This happens when the Org vDC name has a space in it. e.g. "Tenant VDC"
When I change the Org vDC name and remove the space then the network list populates immediately. e.g. "TenantVDC" or "Tenant-VDC"

This is repeatable as an issue.

Please allow spaces in a VDC name.

**Comment by andrew-ni** [comment] 2020-06-23 23:59
Hi @wynner i'll be looking into this and updating this issue

**Comment by wynner** [comment] 2020-06-24 08:37
I'm running:
VCD 10.1.1
CSE 2.6.1 plus the 1.0.1 UI plugin

**Comment by andrew-ni** [comment] 2020-06-26 01:07
Hi @wynner , the issue is that UI plugin was not using the appropriate api query concepts in the vcd api client, which means the query url is not currently being encoded. This bug will exist for ovdcs that have spaces in their names as well.

Working on the fix.

**Comment by andrew-ni** [comment] 2020-07-02 20:52
Follow-up. There is also a bug in VCD that requires the use of `filterEncoded=true` in cases where it was not previously required. We can possibly make a temporary bandaid fix for this issue in a new CSE UI release (1.0.2).

**Comment by andrew-ni** [comment] 2020-07-10 20:46
Fixed in 1.0.2 by manually encoding the affected URLs before making the vcd api call

Affected UI versions: 1.0.0, 1.0.1
Fixed in: 1.0.2

**Closed** 2020-07-14 23:58 UTC
Labels: fixed, known issue, ui
